### ISSUE TITLE
Can't get it to work on Windows

### ISSUE THREAD

**Issue by adam-lynch** [shinnn/gulp-gh-pages#10]
If I try `deploy('https://github.com/adam-lynch/rome-wasnt-built-with-gulp')`, I get the following error:
>
C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\decorators\flow.js:50
                                setTimer(function() { throw e; }, 0);
                                                            ^
>Error: Error: Command failed: error: the following file has changes staged in the index:
    test.txt
(use --cached to keep the file, or -f to force removal)

>  at C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\index.js:148:10
  at tryCatchReject (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:738:14)
  at RejectedHandler.when (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:634:7)
  at DeferredHandler.run (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:417:13)
  at Scheduler._drainQueue (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\scheduler.js:42:14)
  at Scheduler.drainQueue (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\scheduler.js:19:9)
  at process._tickCallback (node.js:415:13)

And if I try `deploy({remoteUrl: 'https://github.com/adam-lynch/rome-wasnt-built-with-gulp'})`, I get the following error:

>C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\decorators\flow.js:50
                                setTimer(function() { throw e; }, 0);
                                                            ^
>Error: Error: Command failed: error: the following file has changes staged in the index:
    test.txt
(use --cached to keep the file, or -f to force removal)

>  at C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\index.js:148:10
  at tryCatchReject (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:738:14)
  at RejectedHandler.when (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:634:7)
  at DeferredHandler.run (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\makePromise.js:417:13)
  at Scheduler._drainQueue (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\scheduler.js:42:14)
  at Scheduler.drainQueue (C:\Users\Adam\Documents\GitHub\rome-wasnt-built-with-gulp\node_modules\gulp-gh-pages\node_modules\when\lib\scheduler.js:19:9)
  at process._tickCallback (node.js:415:13)

---

Also, how does auth work for this? Don't I have to specify it somewhere? Or will this only work on a Mac because the credentials are cached in the command line?

**Comment by shinnn** [comment]
Now this project is tested on AppVeyor (Windows CI) and it passed the last test.

https://ci.appveyor.com/project/ShinnosukeWatanabe/gulp-gh-pages/history
