### ISSUE TITLE
Multiple branches

### ISSUE THREAD

**Issue by dvichris** [shinnn/gulp-gh-pages#65]
I dont know why the issue was closed.. but that doesnt work.

When I try to use git deploy with two different tasks I get an error on the second task.

```
gulp.task('gh-pages', function () {
  return gulp.src('dist/**/*')
    .pipe($.ghPages({
      branch: 'gh-pages'
    }))
});

gulp.task('source', function () {
  return gulp.src('**/*')
    .pipe($.ghPages({
      branch: 'master'
    }))
});
```

```
gulp.task('deploy', function () {
  production = true;
  runSequence('clean', 'build', 'source', 'gh-pages');
});
```

```
[16:55:08] [gulp-master]: Cloning repo
[16:55:08] [gulp-master]: Checkout branch `master`
[16:55:08] [gulp-master]: Copying files to repository
/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
Error: Error: stdout maxBuffer exceeded.
    at /Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/index.js:143:10
    at tryCatchReject (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/admin/Projects/playbook-test/node_modules/gulp-gh-pages/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:355:11)
```

Sorry but I dont know if Im doing something wrong maybe in the syntax of the task?

**Comment by shinnn** [comment]
Duplicate: https://github.com/shinnn/gulp-gh-pages/issues/35

`stdout maxBuffer exceeded.` problem is fixed is the latest version. You're using older version.

**Comment by shinnn** [comment]
> I dont know why the issue was closed

I explained why. https://github.com/shinnn/gulp-gh-pages/issues/64#issuecomment-124847235

> it's not needed

**Comment by dvichris** [comment]
Fixed it by updating although its really slow for some reason I guess it works, thank you for helping me.

**Comment by acierto** [comment]
Still reproducible on version 0.5.4

**Comment by shinnn** [comment]
@acierto :point_right: https://github.com/notatestuser/gift/issues

**Comment by shinnn** [comment]
https://github.com/shinnn/gulp-gh-pages/issues/65#issuecomment-124896223

> Duplicate: #35
