### ISSUE TITLE
Deployment Errors

### ISSUE THREAD

**Issue by dennisgaebel** [shinnn/gulp-gh-pages#68]
I've had some bad luck with deployment using gulp-gh-pages
If an author made the first deployment to gh-pages and then another made deployment each one has a .publish folder locally. The next time either author attempts to deploy these kind of errors are encountered. 

```shell
[14:21:22] 'deploy' errored after 8.61 s
[14:21:22] Error: Command failed: /bin/sh -c git push --set-upstream origin gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/svg-vector-workers/svg-gradient-cleaner.git/'

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

```shell
[14:15:42] Starting 'deploy'...
[14:15:43] [gh-pages] Cloning repo
[14:15:43] [gh-pages] Checkout branch `gh-pages`
[14:15:43] [gh-pages] Updating repository
[14:15:44] 'deploy' errored after 1.44 s
[14:15:44] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: /bin/sh -c git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> gh-pages


Details:
    killed: false
    code: 1
    signal: null
    cmd: /bin/sh -c git pull
```

**Comment by bbohling** [comment]
Our team is also running into this problem. Any suggestions to get around this issue (besides deleting the deployment branch each time)? Or an ETA to a fix?

**Comment by vbud** [comment]
+1

**Comment by lordfpx** [comment]
I don't know if it's related, but I get blocked on the [gh-pages] Updating repository line :-/

**Comment by wcandillon** [comment]
We are also affected by the issue.

**Comment by lordfpx** [comment]
I don't know how I solved that, but I manually updated the .publish folder (pull, push new built files) and, this morning, that was working... kindda strange.

**Comment by bkuzma** [comment]
I'm having this same problem. Should we be checking in the .publish folder to our repositories?

**Comment by armensg** [comment]
Im getting this issue too and im trying to deploy from a different machine

**Comment by michaelonubogu** [comment]
I experienced something similar to this. In my scenario git pull failed because my .publish folder had gotten into a weird state. deleting the .publish folder and re-deploying resolved it
